/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#90003e',
        'primary-fixed': '#ffd9dc',
        'on-secondary-fixed': '#3f0017',
        'on-surface-variant': '#5c3f42',
        'on-primary-fixed': '#400011',
        'tertiary-fixed-dim': '#ffb3b0',
        'surface-container-high': '#eee6e8',
        'surface-container': '#f4ecee',
        'on-background': '#1e1b1c',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'tertiary-container': '#cc4548',
        background: '#fff7f9',
        outline: '#906f72',
        'on-primary-container': '#fffbff',
        tertiary: '#aa2d32',
        'outline-variant': '#e5bdc0',
        'on-surface': '#1e1b1c',
        'on-tertiary-fixed': '#410006',
        'on-secondary': '#ffffff',
        'primary-container': '#e31754',
        error: '#ba1a1a',
        'surface-container-low': '#f9f2f4',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e8e1e3',
        'surface-tint': '#bd0042',
        'surface-bright': '#fff7f9',
        surface: '#fff7f9',
        'inverse-primary': '#ffb2ba',
        'inverse-on-surface': '#f7eff1',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdad8',
        'on-primary-fixed-variant': '#910030',
        'secondary-fixed-dim': '#ffb1c1',
        'surface-container-highest': '#e8e1e3',
        'on-tertiary-fixed-variant': '#8c1520',
        'inverse-surface': '#332f31',
        'secondary-fixed': '#ffd9df',
        'surface-dim': '#dfd8da',
        'secondary-container': '#e50066',
        primary: '#b90040',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        secondary: '#b70050',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#ffb2ba',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        gutter: '1rem',
        'space-md': '1rem',
        margin: '1.25rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'space-xl': '2.25rem',
      },
      // RN needs one font family per weight (no synthetic bolding of custom fonts),
      // so weight is picked via font-jakarta-* instead of embedding it in fontSize like the web mockups did.
      fontFamily: {
        jakarta: ['PlusJakartaSans_400Regular'],
        'jakarta-semibold': ['PlusJakartaSans_600SemiBold'],
        'jakarta-bold': ['PlusJakartaSans_700Bold'],
        'jakarta-extrabold': ['PlusJakartaSans_800ExtraBold'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '14px' }],
        'label-md': ['12px', { lineHeight: '16px' }],
        'body-sm': ['12px', { lineHeight: '16px' }],
        'label-lg': ['14px', { lineHeight: '20px' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'title-md': ['18px', { lineHeight: '24px' }],
        'headline-md': ['20px', { lineHeight: '28px' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px' }],
        'headline-lg': ['28px', { lineHeight: '36px' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px' }],
        'headline-xl': ['40px', { lineHeight: '48px' }],
      },
    },
  },
  plugins: [],
};
