// Mirrors the color tokens in tailwind.config.js — use this where a raw hex
// value is required (icon `color` props, SVG `fill`, etc.) instead of className.
export const colors = {
  primary: '#b90040',
  onPrimary: '#ffffff',
  primaryContainer: '#e31754',
  onPrimaryContainer: '#fffbff',
  primaryFixed: '#ffd9dc',
  primaryFixedDim: '#ffb2ba',
  onPrimaryFixed: '#400011',
  onPrimaryFixedVariant: '#910030',
  secondary: '#b70050',
  onSecondary: '#ffffff',
  secondaryContainer: '#e50066',
  onSecondaryContainer: '#fffbff',
  secondaryFixed: '#ffd9df',
  secondaryFixedDim: '#ffb1c1',
  onSecondaryFixed: '#3f0017',
  onSecondaryFixedVariant: '#90003e',
  tertiary: '#aa2d32',
  onTertiary: '#ffffff',
  tertiaryContainer: '#cc4548',
  onTertiaryContainer: '#fffbff',
  tertiaryFixed: '#ffdad8',
  tertiaryFixedDim: '#ffb3b0',
  onTertiaryFixed: '#410006',
  onTertiaryFixedVariant: '#8c1520',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  background: '#fff7f9',
  onBackground: '#1e1b1c',
  surface: '#fff7f9',
  onSurface: '#1e1b1c',
  surfaceVariant: '#e8e1e3',
  onSurfaceVariant: '#5c3f42',
  surfaceDim: '#dfd8da',
  surfaceBright: '#fff7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f9f2f4',
  surfaceContainer: '#f4ecee',
  surfaceContainerHigh: '#eee6e8',
  surfaceContainerHighest: '#e8e1e3',
  outline: '#906f72',
  outlineVariant: '#e5bdc0',
  inverseSurface: '#332f31',
  inverseOnSurface: '#f7eff1',
  inversePrimary: '#ffb2ba',
  surfaceTint: '#bd0042',
} as const;

export type ThemeColor = keyof typeof colors;
